### ISSUE TITLE
Rewrite of saved data in DAQ

### ISSUE THREAD

**Issue by mjbereyhi** [engelsen/Instrument-control#180] opened 2019-02-07 10:42 UTC
sometimes the rewriting does not work especially for high sampling rate (down sampling factor = 1)

**Comment by mjbereyhi** [comment] 2019-02-07 10:45
In the msgbox that shows for accept or declining the rewrite on a file with the same name, the YES or NO buttons do not work after many clicks.
This happened the same this when the ExpFit was taking very long to analyze (previous issue - issue#179), and was solved by increasing the downsampling factor from 1 to 10.

**Comment by SAFedorov** [comment] 2019-02-07 13:12
I think the problem is just the delay in overwriting large files. But I'm not sure why the delay is so long, will try to investigate.

**Comment by SAFedorov** [comment] 2019-02-08 16:51
Should be fixed now, at least it looks to work as far as I checked. Let me know if you note that it still does not.

**Closed by SAFedorov** 2019-02-08 16:51 UTC
